import React from "react";
import { motion } from "motion/react";
import {
  Sparkles,
  ArrowRight,
  ShieldCheck,
  Zap,
  Terminal,
  Clock,
  CheckCircle2,
  AlertTriangle,
} from "lucide-react";

interface LandingHeroProps {
  onLaunchWorkspace: () => void;
}

export default function LandingHero({ onLaunchWorkspace }: LandingHeroProps) {
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.15,
      },
    },
  };

  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    visible: { y: 0, opacity: 1, transition: { duration: 0.5, ease: "easeOut" } },
  };

  const featureCards = [
    {
      icon: <Clock className="h-6 w-6 text-indigo-400" />,
      title: "AI Workload Analysis",
      description: "Inputs your custom estimated task hours against daily available focus cycles to isolate over-allocation and scheduling conflicts.",
    },
    {
      icon: <Zap className="h-6 w-6 text-amber-400" />,
      title: "AI Rescue Planner",
      description: "Detects active deadline pressure and instantly devises structured, focused daily action blocks.",
    },
    {
      icon: <Terminal className="h-6 w-6 text-rose-400" />,
      title: "AI Decision Log",
      description: "Displays step-by-step reasoning outputs generated by the AI to justify task priority levels.",
    },
  ];

  return (
    <div className="relative overflow-hidden bg-zinc-950 text-white min-h-[calc(100vh-4rem)] flex flex-col justify-center">
      {/* Background gradients */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-7xl h-full pointer-events-none">
        <div className="absolute top-12 left-10 w-96 h-96 bg-indigo-500/10 rounded-full blur-3xl" />
        <div className="absolute bottom-20 right-10 w-96 h-96 bg-violet-600/10 rounded-full blur-3xl" />
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24 relative z-10 flex-grow flex flex-col justify-center">
        <motion.div
          variants={containerVariants}
          initial="hidden"
          animate="visible"
          className="text-center"
        >
          {/* Version badge */}
          <motion.div variants={itemVariants} className="inline-flex items-center gap-1.5 px-3 py-1 bg-zinc-900 border border-zinc-800 rounded-full text-xs font-mono text-zinc-300 mb-8 shadow-inner">
            <Sparkles className="h-3.5 w-3.5 text-indigo-400" />
            <span>Introducing v1.0 • Intelligent Deadline Management</span>
          </motion.div>

          {/* Hero Heading */}
          <motion.h1
            variants={itemVariants}
            className="font-display font-extrabold text-5xl sm:text-7xl lg:text-8xl tracking-tight leading-[0.95] bg-clip-text text-transparent bg-gradient-to-b from-white via-zinc-200 to-zinc-500 max-w-5xl mx-auto"
          >
            Never Miss <br className="hidden sm:inline" /> Another Deadline. <br />
            <span className="bg-clip-text text-transparent bg-gradient-to-r from-indigo-400 via-violet-400 to-cyan-400 text-xl sm:text-4xl lg:text-5xl mt-6 block font-sans font-bold tracking-tight normal-case">
              Your AI Copilot for Beating Deadlines Before They Beat You.
            </span>
          </motion.h1>

          {/* Subheading */}
          <motion.p
            variants={itemVariants}
            className="mt-8 text-zinc-400 text-base sm:text-lg max-w-3xl mx-auto font-sans font-normal leading-relaxed tracking-[-0.01em]"
          >
            DeadlinePilot AI intelligently analyzes your workload, predicts deadline risks, prioritizes tasks, and creates personalized rescue plans so you stay ahead of every deadline.
          </motion.p>

          {/* CTA Buttons */}
          <motion.div
            variants={itemVariants}
            className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4"
          >
            <button
              onClick={onLaunchWorkspace}
              className="font-sans font-semibold tracking-tight text-[15px] w-full sm:w-auto flex items-center justify-center gap-2 px-8 py-4 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl shadow-lg shadow-indigo-500/20 hover:shadow-indigo-500/35 transition-all duration-200"
              id="hero-launch-btn"
            >
              <span>Analyze & Rescue</span>
              <ArrowRight className="h-4 w-4" />
            </button>
            <a
              href="#features-section"
              className="font-sans font-semibold tracking-tight text-[15px] w-full sm:w-auto px-8 py-4 bg-zinc-900/50 hover:bg-zinc-900 text-zinc-300 rounded-xl border border-zinc-800 hover:border-zinc-700 transition-colors duration-200 flex items-center justify-center"
              id="hero-learn-btn"
            >
              See How It Works
            </a>
          </motion.div>

          {/* Interactive UI Mockup Preview */}
          <motion.div
            variants={itemVariants}
            className="mt-16 sm:mt-20 relative max-w-5xl mx-auto rounded-2xl border border-zinc-800/80 bg-zinc-900/35 p-2 backdrop-blur-sm shadow-2xl"
          >
            <div className="absolute inset-x-0 bottom-0 top-1/2 bg-gradient-to-t from-zinc-950 to-transparent z-10 rounded-b-2xl pointer-events-none" />
            <div className="bg-zinc-950 rounded-xl overflow-hidden border border-zinc-800 flex flex-col text-left">
              {/* Fake app chrome */}
              <div className="flex items-center gap-2 px-4 py-3 bg-zinc-900/50 border-b border-zinc-900">
                <div className="w-3 h-3 rounded-full bg-rose-500/40" />
                <div className="w-3 h-3 rounded-full bg-amber-500/40" />
                <div className="w-3 h-3 rounded-full bg-emerald-500/40" />
                <div className="ml-4 text-[11px] font-mono text-zinc-500">deadlinepilot_ai_dashboard.sh</div>
              </div>

              {/* Fake dashboard snippet */}
              <div className="p-6 grid grid-cols-1 md:grid-cols-3 gap-6 font-sans">
                <div className="md:col-span-2 space-y-4">
                  <div className="p-4 rounded-xl border border-zinc-800 bg-zinc-900/20">
                    <div className="flex items-center gap-2 mb-2 text-rose-400 font-mono text-xs">
                      <AlertTriangle className="h-4 w-4" />
                      <span>CRITICAL DEADLINE RISK</span>
                    </div>
                    <h3 className="font-semibold text-white">Stripe Webhook Refactoring</h3>
                    <p className="text-sm text-zinc-400 mt-1">12 hours required • Deadline tomorrow at 18:00</p>
                  </div>
                  <div className="p-4 rounded-xl border border-zinc-800 bg-zinc-900/20 opacity-70">
                    <div className="flex items-center gap-2 mb-2 text-emerald-400 font-mono text-xs">
                      <CheckCircle2 className="h-4 w-4" />
                      <span>ON TRACK</span>
                    </div>
                    <h3 className="font-semibold text-white">Optimize Query Speeds</h3>
                    <p className="text-sm text-zinc-400 mt-1">4 hours required • Deadline in 5 days</p>
                  </div>
                </div>

                <div className="p-4 rounded-xl border border-indigo-500/20 bg-indigo-500/5 flex flex-col justify-between">
                  <div>
                    <span className="text-[10px] font-mono text-indigo-400 font-bold tracking-widest uppercase">AI DECISION CONSOLE</span>
                    <h4 className="text-2xl font-bold mt-2 text-zinc-100">75% Probability</h4>
                    <p className="text-xs text-zinc-400 mt-1 leading-relaxed">System adjusted to Elevated risk. Dedicated action plan suggested.</p>
                  </div>
                  <div className="mt-4 pt-3 border-t border-indigo-500/10 flex justify-between items-center text-xs font-mono text-indigo-300">
                    <span>Rescue Planner: Standard</span>
                    <ShieldCheck className="h-4 w-4 text-indigo-400" />
                  </div>
                </div>
              </div>
            </div>
          </motion.div>
        </motion.div>

        {/* Feature section */}
        <div id="features-section" className="mt-28 border-t border-zinc-900 pt-16 sm:pt-24">
          <div className="text-center max-w-3xl mx-auto">
            <h2 className="font-display font-bold text-3xl tracking-tight text-zinc-200">
              Never Miss Another Milestone
            </h2>
            <p className="text-zinc-500 mt-3 max-w-xl mx-auto">
              Real-time stress relief for developers, freelancers, and product teams.
            </p>
          </div>

          <div className="mt-12 grid grid-cols-1 md:grid-cols-3 gap-8">
            {featureCards.map((feat, idx) => (
              <div
                key={idx}
                className="p-6 rounded-2xl border border-zinc-800 bg-zinc-900/10 hover:bg-zinc-900/35 transition-all duration-200 flex flex-col gap-4 group"
              >
                <div className="p-3 bg-zinc-900 rounded-xl w-fit border border-zinc-800 group-hover:scale-105 transition-transform duration-200">
                  {feat.icon}
                </div>
                <h3 className="font-display font-bold text-lg text-white">
                  {feat.title}
                </h3>
                <p className="text-sm text-zinc-400 leading-relaxed">
                  {feat.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
